/* mega-net from the caller's side. Include this in a C program that has
 * loaded meganet.bin at physical $42000 and meganet_call.bin at MEGANET_TR
 * (see meganet_payload.h, generated by build.py, for both as arrays).
 *
 * Every call goes: stage entry + A/X/Y/Z in the mailbox, call tr_call, read
 * results back. Entries that need more than four bytes take a 28-bit
 * pointer to a parameter block in A/X/Y; for a bank-0 program that is
 * just the 16-bit address with a zero high byte.
 */
#ifndef MEGANET_H
#define MEGANET_H

#include <stdint.h>

#define MEGANET_BASE 0x42000UL          /* where the stack image lives */
/* The trampoline: the stack reserves the page $1600-$16FF of bank 0 in
 * every client. $1600 is inside $1600-$1EFF, which BASIC 65 documents as
 * free for programs, and is the address BASIC programs poke; $0334, the
 * earlier stack's choice, is the KERNAL's own far-call code (REQUIREMENTS.md
 * 5.10). Every address below derives from this one constant. */
#define MEGANET_TR   0x1600U            /* where the trampoline lives */

/* Entry addresses as mapped: $2000 + 3N. These are the ABI. */
#define MEGANET_INIT     0x2000
#define MEGANET_VERSION  0x2003
#define MEGANET_GET_MAC  0x2006
#define MEGANET_LINK_TX  0x2009
#define MEGANET_LINK_RX  0x200C
#define MEGANET_POLL     0x200F
#define MEGANET_SET_IP   0x2012
#define MEGANET_GET_IP   0x2015
#define MEGANET_GET_STATS 0x2018
#define MEGANET_SET_LOCAL_IP4 0x201B
#define MEGANET_DHCP_START 0x201E
#define MEGANET_DHCP_STATE 0x2021
#define MEGANET_GET_DNS    0x2024
#define MEGANET_SET_DNS    0x2027
#define MEGANET_DNS_START  0x202A
#define MEGANET_DNS_STATE  0x202D
#define MEGANET_DNS_RESULT 0x2030
#define MEGANET_NTP_START  0x2033
#define MEGANET_NTP_STATE  0x2036
#define MEGANET_NTP_RESULT 0x2039
#define MEGANET_SET_RTC    0x203C
#define MEGANET_DHCP_LAST_MSG 0x203F
#define MEGANET_TCP_CONNECT 0x2042
#define MEGANET_TCP_STATE   0x2045
#define MEGANET_TCP_SEND    0x2048
#define MEGANET_TCP_RECV    0x204B
#define MEGANET_TCP_CLOSE   0x204E
#define MEGANET_TCP_ABORT   0x2051
#define MEGANET_TCP_LISTEN  0x2054      /* step 6: socket sets (5.11) */
#define MEGANET_TCP_PEER    0x2057
#define MEGANET_TCP_INFO    0x205A
#define MEGANET_UDP_OPEN    0x205D
#define MEGANET_UDP_CLOSE   0x2060
#define MEGANET_UDP_SEND    0x2063
#define MEGANET_UDP_RECV    0x2066

#define MEGANET_TCP_CLOSED 0
#define MEGANET_TCP_SYN_SENT 1
#define MEGANET_TCP_ESTABLISHED 2
#define MEGANET_TCP_CLOSE_WAIT 5
#define MEGANET_TCP_LISTENING 9   /* state; MEGANET_TCP_LISTEN is the entry */
#define MEGANET_TCP_SYN_RCVD 10
#define MEGANET_TCP_F_EOF 0x01
#define MEGANET_TCP_F_RESET 0x02
#define MEGANET_TCP_F_TIMEOUT 0x04
#define MEGANET_TCP_F_REFUSED 0x08

#define MEGANET_DNS_IDLE 0
#define MEGANET_DNS_WAITING 1
#define MEGANET_DNS_DONE 2
#define MEGANET_DNS_FAILED 3
#define MEGANET_NTP_IDLE 0
#define MEGANET_NTP_WAITING 1
#define MEGANET_NTP_DONE 2
#define MEGANET_NTP_FAILED 3

#define MEGANET_DHCP_IDLE 0
#define MEGANET_DHCP_SELECTING 1
#define MEGANET_DHCP_REQUESTING 2
#define MEGANET_DHCP_BOUND 3
#define MEGANET_DHCP_FAILED 4

#define MEGANET_TR_ADDR_LO (*(volatile uint8_t *)(MEGANET_TR + 0x00))
#define MEGANET_TR_ADDR_HI (*(volatile uint8_t *)(MEGANET_TR + 0x01))
#define MEGANET_TR_A       (*(volatile uint8_t *)(MEGANET_TR + 0x02))
#define MEGANET_TR_X       (*(volatile uint8_t *)(MEGANET_TR + 0x03))
#define MEGANET_TR_Y       (*(volatile uint8_t *)(MEGANET_TR + 0x04))
#define MEGANET_TR_Z       (*(volatile uint8_t *)(MEGANET_TR + 0x05))
#define MEGANET_TR_RA      (*(volatile uint8_t *)(MEGANET_TR + 0x06))
#define MEGANET_TR_RX      (*(volatile uint8_t *)(MEGANET_TR + 0x07))
#define MEGANET_TR_RY      (*(volatile uint8_t *)(MEGANET_TR + 0x08))
#define MEGANET_TR_RZ      (*(volatile uint8_t *)(MEGANET_TR + 0x09))
#define MEGANET_TR_MAP_A   (*(volatile uint8_t *)(MEGANET_TR + 0x0A))
#define MEGANET_TR_MAP_X   (*(volatile uint8_t *)(MEGANET_TR + 0x0B))
#define MEGANET_TR_MAP_Y   (*(volatile uint8_t *)(MEGANET_TR + 0x0C))
#define MEGANET_TR_MAP_Z   (*(volatile uint8_t *)(MEGANET_TR + 0x0D))
#define MEGANET_TR_CALL_OFF 0x0E        /* build.py checks this against the link */
#define meganet_tr_call ((void (*)(void))(MEGANET_TR + MEGANET_TR_CALL_OFF))


/* A C caller must take the interrupt vectors from the KERNAL before its
 * first call (REQUIREMENTS.md 5.18): on this core the ethernet
 * controller's events reach the IRQ vector past the I flag, and between
 * calls the KERNAL's handler, entered from a C program's context, comes
 * back with the ROM mapped under the program. meganet_own_vectors() puts
 * a stub in bank 0 under $E000, points the vectors at it, drops the
 * KERNAL from the map and from $01, and tells the trampoline the new
 * map. Call it first, before the trampoline is copied into place, and
 * call meganet_set_restore_map(0, 0xE0, 0, 0) again after the copy,
 * which carries the KERNAL map. The stub records the first interrupted
 * PC and flags at $FF80-$FF82. src/abi/meganet_vectors.c; it needs
 * lpoke and lcopy from mega65-libc. A BASIC caller needs none of this:
 * the KERNAL's handler is right in BASIC's own context. */
void meganet_own_vectors(void);

/* Tell the trampoline what map to restore after each call. The defaults
 * in the trampoline are BASIC 65's SYS map -- $2000-$7FFF identity-mapped,
 * the KERNAL at $E000 from bank 3 -- which is also a running llvm-mos
 * program's, so it is right for BASIC and for any C program that has not
 * remapped (5.4, 5.10). A program that has
 * remapped passes its own MAP register bytes here.
 *
 * To read the current map, the hypervisor's get_mapping trap ($74 to
 * $D640, Y = the page it reports into) returns six bytes: MAPLO high,
 * MAPLO low, MAPHI high, MAPHI low, then two megabyte bytes -- so
 * A = [1], X = [0], Y = [3], Z = [2] (5.4). */
static inline void meganet_set_restore_map(uint8_t a, uint8_t x, uint8_t y,
                                           uint8_t z)
{
    MEGANET_TR_MAP_A = a; MEGANET_TR_MAP_X = x;
    MEGANET_TR_MAP_Y = y; MEGANET_TR_MAP_Z = z;
}

static inline uint8_t meganet_call(uint16_t entry, uint8_t a, uint8_t x,
                                   uint8_t y, uint8_t z)
{
    MEGANET_TR_ADDR_LO = (uint8_t)(entry & 0xff);
    MEGANET_TR_ADDR_HI = (uint8_t)(entry >> 8);
    MEGANET_TR_A = a; MEGANET_TR_X = x; MEGANET_TR_Y = y; MEGANET_TR_Z = z;
    meganet_tr_call();
    return MEGANET_TR_RA;
}

/* Pass a pointer to something in this (bank 0) program. */
static inline uint8_t meganet_call_ptr(uint16_t entry, const void *p)
{
    uint16_t a = (uint16_t)(uintptr_t)p;
    return meganet_call(entry, (uint8_t)(a & 0xff), (uint8_t)(a >> 8), 0, 0);
}

static inline void meganet_ptr28(uint8_t *out, const void *p)
{
    uint16_t a = (uint16_t)(uintptr_t)p;
    out[0] = (uint8_t)(a & 0xff);
    out[1] = (uint8_t)(a >> 8);
    out[2] = 0;
}

/* Parameter blocks. Byte arrays, not structs, for the same reason the
 * stack core uses byte accessors: no reliance on layout. */
typedef struct { uint8_t ptr[3]; uint8_t len[2]; } meganet_link_tx_t;
typedef struct { uint8_t ptr[3]; uint8_t cap[2]; uint8_t len[2]; } meganet_link_rx_t;

static inline uint8_t meganet_link_tx(const void *frame, uint16_t len)
{
    meganet_link_tx_t b;
    meganet_ptr28(b.ptr, frame);
    b.len[0] = (uint8_t)(len & 0xff); b.len[1] = (uint8_t)(len >> 8);
    return meganet_call_ptr(MEGANET_LINK_TX, &b);
}

/* Returns 1 and sets *len if a frame was copied to buf. */
static inline uint8_t meganet_link_rx(void *buf, uint16_t cap, uint16_t *len)
{
    meganet_link_rx_t b;
    uint8_t got;
    meganet_ptr28(b.ptr, buf);
    b.cap[0] = (uint8_t)(cap & 0xff); b.cap[1] = (uint8_t)(cap >> 8);
    b.len[0] = b.len[1] = 0;
    got = meganet_call_ptr(MEGANET_LINK_RX, &b);
    *len = (uint16_t)(b.len[0] | ((uint16_t)b.len[1] << 8));
    return got;
}

typedef struct { uint8_t ip[4], mask[4], gw[4]; } meganet_ipconf_t;
typedef struct { uint8_t rx[2], arp_replies[2], echo_replies[2], tx_failures[2],
                 arp_learned[2], udp_rx[2], udp_dropped[2], dhcp_tries[2],
                 dhcp_rx[2], dhcp_last_len[2], dhcp_last_op, dhcp_last_type,
                 dhcp_last_xid[4], dhcp_xid[4], dhcp_last_chaddr0, dhcp_last_chaddr5,
                 window_irqs[2], tcp_rst_sent[2]; } meganet_stats_t;   /* appended in 5.11 */

static inline uint8_t meganet_set_ip(const meganet_ipconf_t *c)
{ return meganet_call_ptr(MEGANET_SET_IP, c); }

static inline uint8_t meganet_get_stats(meganet_stats_t *s)
{ return meganet_call_ptr(MEGANET_GET_STATS, s); }

static inline uint8_t meganet_dhcp_start(void)
{ return meganet_call(MEGANET_DHCP_START, 0, 0, 0, 0); }
static inline uint8_t meganet_dhcp_state(void)
{ return meganet_call(MEGANET_DHCP_STATE, 0, 0, 0, 0); }
/* state in the return; *phase (0 bound, 1 renewing, 2 rebinding) and
 * *lease_left in minutes (65535 = no expiry) optional. Renewal runs by
 * itself while you poll; an expired lease drops the address and the state
 * leaves BOUND until a new one is granted. */
static inline uint8_t meganet_dhcp_status(uint8_t *phase, uint16_t *lease_left)
{ uint8_t st = meganet_call(MEGANET_DHCP_STATE, 0, 0, 0, 0);
  if (phase) *phase = MEGANET_TR_RX;
  if (lease_left) *lease_left = (uint16_t)(MEGANET_TR_RY | ((uint16_t)MEGANET_TR_RZ << 8));
  return st; }
static inline uint8_t meganet_get_ip(meganet_ipconf_t *c)
{ return meganet_call_ptr(MEGANET_GET_IP, c); }
static inline uint8_t meganet_get_dns(uint8_t *dns4)
{ return meganet_call_ptr(MEGANET_GET_DNS, dns4); }

/* weekday is 0 = Sunday in both blocks; SET_RTC writes it to the clock as given */
typedef struct { uint8_t offset_min[2]; uint8_t seconds[4]; uint8_t year[2];
                 uint8_t month, day, hour, minute, second, weekday; } meganet_time_t;
typedef struct { uint8_t year[2]; uint8_t month, day, hour, minute, second, weekday; } meganet_rtc_t;

static inline uint8_t meganet_dns_start(const char *name)
{ return meganet_call_ptr(MEGANET_DNS_START, name); }
static inline uint8_t meganet_dns_state(void)
{ return meganet_call(MEGANET_DNS_STATE, 0, 0, 0, 0); }
static inline void meganet_dns_result(uint8_t *ip4)
{ meganet_call(MEGANET_DNS_RESULT, 0, 0, 0, 0);
  ip4[0] = MEGANET_TR_RA; ip4[1] = MEGANET_TR_RX; ip4[2] = MEGANET_TR_RY; ip4[3] = MEGANET_TR_RZ; }
static inline uint8_t meganet_ntp_start(const uint8_t *ip4)
{ return meganet_call(MEGANET_NTP_START, ip4[0], ip4[1], ip4[2], ip4[3]); }
static inline uint8_t meganet_ntp_state(void)
{ return meganet_call(MEGANET_NTP_STATE, 0, 0, 0, 0); }
static inline uint8_t meganet_ntp_result(meganet_time_t *t)
{ return meganet_call_ptr(MEGANET_NTP_RESULT, t); }
static inline uint8_t meganet_set_rtc(const meganet_rtc_t *r)
{ return meganet_call_ptr(MEGANET_SET_RTC, r); }

typedef struct { uint8_t ip[4], port[2]; } meganet_tcp_addr_t;

/* Sockets. Every TCP entry takes the socket index in Z; the helpers
 * without a socket argument use socket 0, which is all a client that
 * predates socket sets ever had. A socket that listens goes ESTABLISHED
 * when a peer connects and CLOSED when that connection ends; listen again
 * to take another. */
static inline uint8_t meganet_tcp_connect_s(uint8_t s, const uint8_t *ip4, uint16_t port)
{ meganet_tcp_addr_t a; uint16_t p = (uint16_t)(uintptr_t)&a;
  a.ip[0]=ip4[0]; a.ip[1]=ip4[1]; a.ip[2]=ip4[2]; a.ip[3]=ip4[3];
  a.port[0] = (uint8_t)port; a.port[1] = (uint8_t)(port >> 8);
  return meganet_call(MEGANET_TCP_CONNECT, (uint8_t)p, (uint8_t)(p >> 8), 0, s); }
static inline uint8_t meganet_tcp_listen(uint8_t s, uint16_t port)
{ return meganet_call(MEGANET_TCP_LISTEN, (uint8_t)port, (uint8_t)(port >> 8), 0, s); }
/* state in the return; *flags and *avail optional */
static inline uint8_t meganet_tcp_state_s(uint8_t s, uint8_t *flags, uint16_t *avail)
{ uint8_t st = meganet_call(MEGANET_TCP_STATE, 0, 0, 0, s);
  if (flags) *flags = MEGANET_TR_RX;
  if (avail) *avail = (uint16_t)(MEGANET_TR_RY | ((uint16_t)MEGANET_TR_RZ << 8));
  return st; }
static inline void meganet_tcp_peer(uint8_t s, uint8_t *ip4, uint16_t *port)
{ meganet_tcp_addr_t a; uint16_t p = (uint16_t)(uintptr_t)&a;
  meganet_call(MEGANET_TCP_PEER, (uint8_t)p, (uint8_t)(p >> 8), 0, s);
  ip4[0]=a.ip[0]; ip4[1]=a.ip[1]; ip4[2]=a.ip[2]; ip4[3]=a.ip[3];
  if (port) *port = (uint16_t)(a.port[0] | ((uint16_t)a.port[1] << 8)); }
/* sockets in the return; *where = 1 attic RAM, 2 bank 5; *base12 = pool base >> 12 */
static inline uint8_t meganet_tcp_info(uint8_t *where, uint16_t *base12)
{ uint8_t n = meganet_call(MEGANET_TCP_INFO, 0, 0, 0, 0);
  if (where) *where = MEGANET_TR_RX;
  if (base12) *base12 = (uint16_t)(MEGANET_TR_RY | ((uint16_t)MEGANET_TR_RZ << 8));
  return n; }
static inline uint16_t meganet_tcp_send_s(uint8_t s, const void *data, uint16_t len)
{ meganet_link_tx_t b; uint16_t p = (uint16_t)(uintptr_t)&b; meganet_ptr28(b.ptr, data);
  b.len[0] = (uint8_t)len; b.len[1] = (uint8_t)(len >> 8);
  meganet_call(MEGANET_TCP_SEND, (uint8_t)p, (uint8_t)(p >> 8), 0, s);
  return (uint16_t)(MEGANET_TR_RA | ((uint16_t)MEGANET_TR_RX << 8)); }
static inline uint16_t meganet_tcp_recv_s(uint8_t s, void *buf, uint16_t cap)
{ meganet_link_rx_t b; uint16_t p = (uint16_t)(uintptr_t)&b; meganet_ptr28(b.ptr, buf);
  b.cap[0] = (uint8_t)cap; b.cap[1] = (uint8_t)(cap >> 8); b.len[0] = b.len[1] = 0;
  meganet_call(MEGANET_TCP_RECV, (uint8_t)p, (uint8_t)(p >> 8), 0, s);
  return (uint16_t)(b.len[0] | ((uint16_t)b.len[1] << 8)); }
static inline void meganet_tcp_close_s(uint8_t s) { meganet_call(MEGANET_TCP_CLOSE, 0, 0, 0, s); }
static inline void meganet_tcp_abort_s(uint8_t s) { meganet_call(MEGANET_TCP_ABORT, 0, 0, 0, s); }

/* Socket 0, for the single-connection client. */
static inline uint8_t meganet_tcp_connect(const uint8_t *ip4, uint16_t port)
{ return meganet_tcp_connect_s(0, ip4, port); }
static inline uint8_t meganet_tcp_state(uint8_t *flags, uint16_t *avail)
{ return meganet_tcp_state_s(0, flags, avail); }
static inline uint16_t meganet_tcp_send(const void *data, uint16_t len)
{ return meganet_tcp_send_s(0, data, len); }
static inline uint16_t meganet_tcp_recv(void *buf, uint16_t cap)
{ return meganet_tcp_recv_s(0, buf, cap); }
static inline void meganet_tcp_close(void) { meganet_tcp_close_s(0); }
static inline void meganet_tcp_abort(void) { meganet_tcp_abort_s(0); }

/* UDP sockets: open returns an index or $FF; the index goes in Z. */
typedef struct { uint8_t ip[4], port[2], ptr[3], len[2]; } meganet_udp_tx_t;
typedef struct { uint8_t ptr[3], cap[2], len[2], src_ip[4], src_port[2]; } meganet_udp_rx_t;
#define MEGANET_SEND_FAILED 0
#define MEGANET_SEND_OK 1
#define MEGANET_SEND_PENDING 2   /* next hop being resolved: send again */
static inline uint8_t meganet_udp_open(uint16_t port)
{ return meganet_call(MEGANET_UDP_OPEN, (uint8_t)port, (uint8_t)(port >> 8), 0, 0); }
static inline void meganet_udp_close(uint8_t s) { meganet_call(MEGANET_UDP_CLOSE, 0, 0, 0, s); }
static inline uint8_t meganet_udp_send(uint8_t s, const uint8_t *ip4, uint16_t port,
                                       const void *data, uint16_t len)
{ meganet_udp_tx_t b; uint16_t p = (uint16_t)(uintptr_t)&b;
  b.ip[0]=ip4[0]; b.ip[1]=ip4[1]; b.ip[2]=ip4[2]; b.ip[3]=ip4[3];
  b.port[0] = (uint8_t)port; b.port[1] = (uint8_t)(port >> 8);
  meganet_ptr28(b.ptr, data); b.len[0] = (uint8_t)len; b.len[1] = (uint8_t)(len >> 8);
  return meganet_call(MEGANET_UDP_SEND, (uint8_t)p, (uint8_t)(p >> 8), 0, s); }
/* Returns 1 and fills *len, src_ip4, *src_port if a datagram was waiting. */
static inline uint8_t meganet_udp_recv(uint8_t s, void *buf, uint16_t cap, uint16_t *len,
                                       uint8_t *src_ip4, uint16_t *src_port)
{ meganet_udp_rx_t b; uint16_t p = (uint16_t)(uintptr_t)&b; uint8_t got;
  meganet_ptr28(b.ptr, buf); b.cap[0] = (uint8_t)cap; b.cap[1] = (uint8_t)(cap >> 8);
  got = meganet_call(MEGANET_UDP_RECV, (uint8_t)p, (uint8_t)(p >> 8), 0, s);
  if (len) *len = (uint16_t)(b.len[0] | ((uint16_t)b.len[1] << 8));
  if (src_ip4) { src_ip4[0]=b.src_ip[0]; src_ip4[1]=b.src_ip[1]; src_ip4[2]=b.src_ip[2]; src_ip4[3]=b.src_ip[3]; }
  if (src_port) *src_port = (uint16_t)(b.src_port[0] | ((uint16_t)b.src_port[1] << 8));
  return got; }

/* The network pump: call it as often as you can. Returns 1 if a frame was
 * handled this call. */
static inline uint8_t meganet_poll(void)
{ return meganet_call(MEGANET_POLL, 0, 0, 0, 0); }

#endif
